{% set name = "lightning" %}
{% set version = "2.5.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f720fe4f6d03a7f15f9aef3112c5a0d1eafd8d27b903f4a1354b609685b2ec70

build:
  entry_points:
    - fabric = lightning.fabric.cli:_main
    - lightning = lightning.fabric.cli:_legacy_main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    # The pinnings below are extracted from lightning.egg-info/requires.txt
    # This is because the requirements under requirements/ are transformed
    # before being used by the setup script
    - pyyaml >=5.4,<8.0
    ## fsspec[http] ##
    - fsspec >=2022.5.0,<2026.0
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - requests
    ## fsspec[http] ##
    - lightning-utilities >=0.10.0,<2.0
    - numpy >=1.17.2,<3.0
    - packaging >=20.0,<25.0
    - pytorch >=2.1.0,<4.0
    - torchmetrics >=0.7.0,<3.0
    - tqdm >=4.57.0,<6.0
    - typing-extensions >=4.4.0,<6.0
    - pytorch-lightning
    # click is necessary to use the entry-points
    - click

test:
  imports:
    - lightning
  commands:
    - pip check
    - lightning --help
    - fabric --help
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/pytorch-lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  description: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
  dev_url: https://github.com/Lightning-AI/pytorch-lightning
  doc_url: https://lightning.ai/docs/app/stable/

extra:
  recipe-maintainers:
    - Borda
    - weiji14
