{% set name = "lightning" %}
{% set version = "2.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 881841716b59c1837ae0c562c2e64fea9bcf49ef9de3867bd1f868557ec23d04
  - url: https://github.com/Lightning-AI/pytorch-{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: 2761a16d362ac604798e230883a81b54ed301ef45eea4b93a58ced79feb50760
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - fabric = lightning.fabric.cli:_main
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - packaging
  run:
    - python
    # The pinnings below are extracted from src/lightning.egg-info/requires.txt
    # This is because the requirements under requirements/ are transformed
    # before being used by the setup script
    - pyyaml >=5.4,<8.0
    - fsspec >=2022.5.0,<2027.0
    - aiohttp !=4.0.0a0,!=4.0.0a1
    #- requests
    - lightning-utilities >=0.10.0,<2.0
    #- numpy >=1.17.2,<3.0
    - packaging >=20.0,<27.0
    # By default pytorch try to resolve gpu version:
    # Trying to find MPS symbol : _C.cpython-310-darwin.so, 0x0002: Symbol not found: __ZN2at3mps14getMPSProfilerEv
    - pytorch-cpu >=2.1.0,<4.0
    - torchmetrics >=0.7.0,<3.0
    - tqdm >=4.57.0,<6.0
    - typing-extensions >=4.5.0,<6.0
    - pytorch-lightning
    # click is necessary to use the entry-points
    - click

test:
  source_files:
    - gh_src/tests
  imports:
    - lightning
  commands:
    - pip check
    - fabric --help
    - pytest -v gh_src/tests/tests_fabric
  requires:
    - pip
    - pytest ==8.4.2
    - cloudpickle >=1.3,<4.0
    - tensorboard >=2.11,<3.0

about:
  home: https://github.com/Lightning-AI/pytorch-lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  description: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
  dev_url: https://github.com/Lightning-AI/pytorch-lightning
  doc_url: https://lightning.ai/docs/app/stable

extra:
  recipe-maintainers:
    - Borda
    - weiji14
